<a href="https://colab.research.google.com/github/shagun14/Data-Analysis/blob/main/Assignment-6-Theory.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h4>Question 1</h4>
Purpose and Advantages of Numpy:
<br>
<ol>
<li>Efficient array handling: NumPy introduces the ndarray object, which is a fast, flexible container for large data sets in Python. This allows users to work with large arrays and matrices efficiently.</li>
<li>Numerical Computations: It provides a range of functions for performing mathematical operations on arrays, making it easier to implement complex numerical computations.</li>
<li>Interoperability: NumPy arrays are designed to integrate seamlessly with other scientific computing libraries, such as SciPy, Pandas, and Matplotlib, enabling a more robust analytical framework.</li>
<li>Memory Efficiency: NumPy arrays require less memory than traditional Python lists. This is particularly beneficial when working with large datasets, as it allows for better memory management and performance.</li>
<li>Convenience: NumPy provides a wide array of functions for mathematical operations, statistical analysis, and linear algebra, simplifying the coding process. It also supports broadcasting, which allows for operations between arrays of different shapes.</li><br>
Enhancements to Python's Capabilities:
<ol>
<li>N-dimensional Arrays: Unlike Python lists, which are one-dimensional, NumPy allows the creation of multi-dimensional arrays, enabling more complex data structures.</li>
<li>Broadcasting: This feature allows operations on arrays of different shapes without the need for explicit replication of data, making coding more efficient and intuitive.</li>
<li>Universal Functions (ufuncs): NumPy provides a set of vectorized functions that operate on entire arrays, greatly enhancing performance for element-wise operations.</li>




<h4>Question 2</h4>
np.mean() and np.average() are functions in NumPy that calculate the average of the elements present in an array.<br>
<br>
np.mean(): It computes the arithmetic mean of the elements along a specified axis of an array. It is needed when you need a straightforward average calculation without any weights. It is the simplest and most efficient method to calculate the mean.<br>
np.average(): It computes the weighted average of an array. If no weights are provided, it behaves similar to np.mean(). It is useful in scenarios when you need to calculate a weighted average, where some elements contribute more to the average than others.

<h4>Question 3</h4>
Reversing a 1D array: It can be done using slicing

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5])
reversed_arr = arr[::-1]

print("Original Array", arr)
print("Reversed Array", reversed_arr)


Original Array [1 2 3 4 5]
Reversed Array [5 4 3 2 1]


Reversing a 2D array: It can be along specific axes using slicing.

In [ ]:
arr1 = np.array([[1,2,3,],[4,5,6],[7,8,9]])
reversed_arr1 = arr1[::-1]
reversed_arr2 = arr1[:, ::-1]

print("Original Array", arr1)
print("Reversed Array along first axis", reversed_arr1)
print("Reversed Array along second axis", reversed_arr2)

Original Array [[1 2 3]
 [4 5 6]
 [7 8 9]]
Reversed Array along first axis [[7 8 9]
 [4 5 6]
 [1 2 3]]
Reversed Array along second axis [[3 2 1]
 [6 5 4]
 [9 8 7]]


<h4>Question 4</h4>
You can determine the data type of elements in an array using the .dtype attribute of the array.

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5])
data_type = arr.dtype

print("Data Type:", data_type)

Data Type: int64


Importance of Data Types
<ol>
<li>Memory Management</li>
<ul>
<li> Efficiency: Different data types require different amounts of memory. For instance, an int32 takes up 4 bytes, while an int64 takes 8 bytes. Using an appropriate data type minimizes memory usage, which is especially important when dealing with large datasets.</li>
<li> Avoiding Overflow: Choosing a data type that is too small for the data can lead to overflow errors. For example, using int8 for values larger than 127 will result in incorrect values.</li>
</ul>

<li>Performance:</li>
<ul>
<li>Computation Speed: Operations on smaller data types can be faster. For instance, performing calculations on float32 arrays is typically faster than on float64 due to reduced data size, which can lead to better cache performance.</li>
<li>Vectorized Operations: NumPy’s vectorized operations are optimized for specific data types. Using the correct data type can enhance the performance of these operations significantly.</li>
</ul>
</ol>

<h4>Question 5:</h4>
An ndarray is a multidimensional, homogeneous array of fixed-size items. It can represent a range of data types, including integers, floats, and even complex numbers. The "n" in ndarrays refers to the number of dimensions (axes) the array can have, allowing for representation of scalars (0D), vectors (1D), matrices (2D), and higher-dimensional data.<br>
<br>
<b>Key Features of ndarrays</b>
<ol>
<li>Homogeneity: All elements in an ndarray must be of the same data type, which allows for more efficient storage and computation.</li>
<li>Multidimensional: Ndarrays can have any number of dimensions (1D, 2D, 3D, etc.). This flexibility makes it easier to represent complex data structures.</li>
<li>Indexing and Slicing: Ndarrays provide powerful indexing and slicing capabilities, enabling easy access to subarrays and specific elements.</li>
<li>Methods and Functions: NumPy provides a rich set of functions and methods for performing mathematical operations, statistical analysis, and linear algebra on ndarrays.</li>
</ol>
<br>
<br>
Differences from standard python lists:<br>
<ol>
<li>Homogeneity and Heterogeneity:</li>
<ul>
<li>ndarray: all elements are of same type</li>
<li>List: can contain elements of different types</li>
</ul>
<li>Performance:</li>
<ul>
<li>ndarray: Optimized for numerical computations and operations, typically faster than lists for large datasets due to internal optimizations and vectorization.</li>
<li>List: Slower for numerical computations, especially with large datasets, as operations typically involve iterating over each element.
</li>
</ul>
<li>Multidimensionality:</li>
<ul>
<li> ndarray: Naturally supports multiple dimensions.</li>
<li> List: While lists can be nested to simulate multidimensional arrays, they do not have built-in support for n-dimensionality.</li>
</ul>
<li>Memory Management:</li>
<ul>
<li>ndarray: More efficient memory usage due to contiguous storage of elements and fixed data types.</li>
<li>List: Less efficient as they store pointers to objects, which can lead to increased memory overhead.</li>

<h4> Question 6</h4>
the performance benefits of NumPy arrays over Python lists for large-scale numerical operations include;<br>
<ul>
<li>Memory Efficiency: Contiguous storage and fixed data types reduce overhead.</li>
<li>Speed: Vectorization enables fast computations without explicit loops.</li>
<li>Broadcasting: Simplifies operations on arrays of different shapes.</li>
<li>Reduced Overhead: Less function call and type-checking overhead compared to Python lists.</li>
<li>Parallelization: Leverage optimized libraries for enhanced performance.</li>
These advantages make NumPy arrays the preferred choice for scientific computing, data analysis, and any application that requires intensive numerical calculations.

<h4>Question 7</h4>
vstack()<br>
Functionality: Stacks arrays in sequence vertically (row-wise).<br>
Input: Requires a sequence of arrays with the same shape along all but the first axis.

In [ ]:
import numpy as np

# Create two 2D arrays
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

# Stack arrays vertically
result_vstack = np.vstack((array1, array2))

print("Result of vstack:")
print(result_vstack)

Result of vstack:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


hstack()<br>
Functionality: Stacks arrays in sequence horizontally (column-wise).<br>
Input: Requires a sequence of arrays with the same shape along all but the second axis.

In [ ]:
import numpy as np

# Create two 2D arrays
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[7, 8],
                   [9, 10]])

# Stack arrays horizontally
result_hstack = np.hstack((array1, array2))

print("Result of hstack:")
print(result_hstack)

Result of hstack:
[[ 1  2  3  7  8]
 [ 4  5  6  9 10]]


<h4>Question 8</h4>
fliplr() and flipud() are functions used to flip arrays in specific directions.<br>
Effect on 1D Arrays: Both will reverse the order, but they are intended for 2D contexts.<br>
fliplr()
<li>Functionality: Flips an array left to right (horizontally).</li>
<li>Applicable Dimension: Primarily operates on 2D arrays (matrices). For 1D arrays, it will reverse the order of the elements.</li>

In [10]:
import numpy as np

# Create a 2D array
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6]])

# Flip the array left to right
result_fliplr = np.fliplr(array_2d)

print("Original Array:\n", array_2d)
print("Result of fliplr:\n", result_fliplr)

Original Array:
 [[1 2 3]
 [4 5 6]]
Result of fliplr:
 [[3 2 1]
 [6 5 4]]


flipud()
<li>Functionality: Flips an array up to down (vertically).</li>
<li>Applicable Dimension: Also primarily operates on 2D arrays. For 1D arrays, it will reverse the order of the elements.</li>


In [11]:
import numpy as np

# Create a 2D array
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6]])

# Flip the array up to down
result_flipud = np.flipud(array_2d)

print("Original Array:\n", array_2d)
print("Result of flipud:\n", result_flipud)


Original Array:
 [[1 2 3]
 [4 5 6]]
Result of flipud:
 [[4 5 6]
 [1 2 3]]


<h4>Question 9</h4>
The array_split() method in NumPy is used to divide an array into multiple sub-arrays along a specified axis. It offers flexibility in how an array can be split, particularly when dealing with uneven splits.<br>
The method takes an input array and the number of sections to split it into. It can split arrays along any axis.<br>
Syntax: numpy.array_split(ary, indices_or_sections, axis=0)<br>
<h4>Handling uneven splits</h4>
When splitting an array into a specified number of sections, if the array cannot be evenly divided, array_split() will distribute the elements as evenly as possible. The first few sub-arrays will receive one more element than the remaining sub-arrays.


In [12]:
import numpy as np

# Create a 1D array
array_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# Split into 3 sections
result = np.array_split(array_1d, 3)

print("Original Array:", array_1d)
print("Result of array_split (3 sections):")
for i, arr in enumerate(result):
    print(f"Section {i+1}:", arr)

Original Array: [1 2 3 4 5 6 7 8]
Result of array_split (3 sections):
Section 1: [1 2 3]
Section 2: [4 5 6]
Section 3: [7 8]


<h4>Question 10</h4>
Vectorization and broadcasting are two fundamental concepts in NumPy that significantly enhance the efficiency of array operations. They allow for concise, readable code and reduce the need for explicit loops, leading to improved performance, especially with large datasets.<br>
<li>Performance: Operations on entire arrays are typically much faster than using loops because they are optimized and executed in compiled code.</li>
<li>Conciseness: Code is shorter and easier to read, making it simpler to understand and maintain.</li>
<br>
Broadcasting is a powerful mechanism that allows NumPy to perform operations on arrays of different shapes. When performing operations between arrays, NumPy automatically expands the smaller array to match the shape of the larger array.
<li>Flexibility: It allows for more flexible operations without needing to manually reshape arrays.</li>
<li>Efficiency: Reduces the need for duplicating data, thus saving memory.</li>
<br>
<h5>Contributions to Efficient Array Operations</h5>
<li>Performance: Both vectorization and broadcasting reduce the computational overhead associated with Python loops, leveraging optimized, compiled code for array operations.</li>
<li>Code Simplicity: They enable writing cleaner and more understandable code by reducing the need for intricate looping constructs.</li>
<li>Memory Efficiency: Broadcasting avoids unnecessary duplication of data, which is particularly advantageous when working with large arrays.</li>