<a href="https://colab.research.google.com/github/shagun14/Data-Analysis/blob/main/Assignment-6-Practical.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Question 1

In [1]:
import numpy as np

# Create a 3x3 array with random integers between 1 and 100
array = np.random.randint(1, 101, size=(3, 3))
print("Original Array:\n", array)

# Interchange rows and columns (transpose the array)
transposed_array = np.transpose(array)
# Alternatively, you can use array.T
# transposed_array = array.T

print("\nTransposed Array:\n", transposed_array)

Original Array:
 [[79 57 72]
 [18  1 93]
 [25 60 84]]

Transposed Array:
 [[79 18 25]
 [57  1 60]
 [72 93 84]]


Question 2

In [2]:
import numpy as np

# Generate a 1D array with 10 elements
array_1d = np.arange(10)  # This creates an array with values from 0 to 9
print("Original 1D Array:\n", array_1d)

# Reshape it into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)
print("\nReshaped to 2x5 Array:\n", array_2x5)

# Reshape it into a 5x2 array
array_5x2 = array_1d.reshape(5, 2)
print("\nReshaped to 5x2 Array:\n", array_5x2)

Original 1D Array:
 [0 1 2 3 4 5 6 7 8 9]

Reshaped to 2x5 Array:
 [[0 1 2 3 4]
 [5 6 7 8 9]]

Reshaped to 5x2 Array:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


Question 3:

In [3]:
import numpy as np

# Create a 4x4 array with random float values
array_4x4 = np.random.rand(4, 4)
print("Original 4x4 Array:\n", array_4x4)

# Add a border of zeros around the 4x4 array
array_with_border = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)
print("\n6x6 Array with Border of Zeros:\n", array_with_border)

Original 4x4 Array:
 [[0.38605551 0.33227848 0.36447716 0.59356067]
 [0.37393415 0.75785879 0.18599568 0.57496383]
 [0.62638028 0.11706307 0.53496475 0.81862824]
 [0.86146014 0.59774319 0.42225659 0.33715377]]

6x6 Array with Border of Zeros:
 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.38605551 0.33227848 0.36447716 0.59356067 0.        ]
 [0.         0.37393415 0.75785879 0.18599568 0.57496383 0.        ]
 [0.         0.62638028 0.11706307 0.53496475 0.81862824 0.        ]
 [0.         0.86146014 0.59774319 0.42225659 0.33715377 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


Question 4:

In [4]:
import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
array = np.arange(10, 61, 5)
print("Array of integers from 10 to 60 with a step of 5:\n", array)

Array of integers from 10 to 60 with a step of 5:
 [10 15 20 25 30 35 40 45 50 55 60]


Question 5:

In [5]:
import numpy as np

# Create a NumPy array of strings
string_array = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
uppercase_array = np.char.upper(string_array)
lowercase_array = np.char.lower(string_array)
titlecase_array = np.char.title(string_array)

# Print the results
print("Original Array:\n", string_array)
print("\nUppercase Array:\n", uppercase_array)
print("\nLowercase Array:\n", lowercase_array)
print("\nTitlecase Array:\n", titlecase_array)

Original Array:
 ['python' 'numpy' 'pandas']

Uppercase Array:
 ['PYTHON' 'NUMPY' 'PANDAS']

Lowercase Array:
 ['python' 'numpy' 'pandas']

Titlecase Array:
 ['Python' 'Numpy' 'Pandas']


Question 6:


In [6]:
import numpy as np

# Create a NumPy array of words
words_array = np.array(['hello', 'world', 'numpy', 'python'])

# Insert a space between each character of every word
spaced_words_array = np.char.join(' ', words_array)

# Print the results
print("Original Array of Words:\n", words_array)
print("\nArray with Spaces Between Characters:\n", spaced_words_array)

Original Array of Words:
 ['hello' 'world' 'numpy' 'python']

Array with Spaces Between Characters:
 ['h e l l o' 'w o r l d' 'n u m p y' 'p y t h o n']


Question 7:

In [7]:
import numpy as np

# Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])

array2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

# Perform element-wise operations
addition_result = array1 + array2
subtraction_result = array1 - array2
multiplication_result = array1 * array2
division_result = array1 / array2

# Print the results
print("Array 1:\n", array1)
print("\nArray 2:\n", array2)
print("\nElement-wise Addition:\n", addition_result)
print("\nElement-wise Subtraction:\n", subtraction_result)
print("\nElement-wise Multiplication:\n", multiplication_result)
print("\nElement-wise Division:\n", division_result)

Array 1:
 [[1 2 3]
 [4 5 6]]

Array 2:
 [[ 7  8  9]
 [10 11 12]]

Element-wise Addition:
 [[ 8 10 12]
 [14 16 18]]

Element-wise Subtraction:
 [[-6 -6 -6]
 [-6 -6 -6]]

Element-wise Multiplication:
 [[ 7 16 27]
 [40 55 72]]

Element-wise Division:
 [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


Question 8:

In [9]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)
print("5x5 Identity Matrix:\n", identity_matrix)

# Extract the diagonal elements
diagonal_elements = np.diag(identity_matrix)
print("\nDiagonal Elements:\n", diagonal_elements)

5x5 Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
 [1. 1. 1. 1. 1.]


Question 9

In [8]:
import numpy as np

random_integers = np.random.randint(0, 1001, size=100)
print("Random Integers Array:\n", random_integers)

def is_prime(num):
    if num <= 1:
        return False
    for i in range(2, int(num**0.5) + 1):
        if num % i == 0:
            return False
    return True

prime_numbers = [num for num in random_integers if is_prime(num)]

print("\nPrime Numbers in the Array:\n", prime_numbers)

Random Integers Array:
 [712 575 719 290 150 879 959 618 807 888 618 106  57 449 926   8 661 392
 288 220 691 182 182 247 280 986 883 421 414 586 601 765 693 638 817 189
 519 463 479 676 262 752  83 700 191 453 824 613 684 655 265 622 425 808
 653 384 741 190 116 168 512 819 496  70 448 414 251 618 281  87 558 651
 532 790  66 848 951 218 885 511  90 349 576 137 356 650 424 184 991 245
 722 372 485 306  69 122 227 815 326 698]

Prime Numbers in the Array:
 [719, 449, 661, 691, 883, 421, 601, 463, 479, 83, 191, 613, 653, 251, 281, 349, 137, 991, 227]


Question 10:


In [10]:
import numpy as np

daily_temperatures = np.random.randint(20, 36, size=30)
print("Daily Temperatures for the Month:\n", daily_temperatures)

weekly_temperatures = daily_temperatures[:28].reshape(4, 7)

weekly_averages = np.mean(weekly_temperatures, axis=1)

print("\nWeekly Averages:\n", weekly_averages)

Daily Temperatures for the Month:
 [22 21 30 28 33 29 34 28 26 23 21 33 22 26 31 23 33 21 32 30 24 21 28 21
 24 27 33 23 35 30]

Weekly Averages:
 [28.14285714 25.57142857 27.71428571 25.28571429]
